#!/usr/bin/perl

#
# WineTest Index Script
# by Jeremy Newman <jnewman@codeweavers.com>
#

# load CGI object
use CGI qw(:standard);
my $q = new CGI;

# change url based on testing vars
if ($q->param('testing')) {

    my @builds;
    # read testing dir
    opendir(DIR, "./data/");
    foreach my $build (readdir(DIR))
    {
        next if $build =~ /^\./;
        next unless $build =~ /^[-.0-9a-zA-Z]+$/;
        next unless -f "./data/$build/index.html";
        push @builds, { name => $build, date => (stat "./data/$build")[9] };
    }
    closedir(DIR);
    @builds = sort { $a->{date} <=> $b->{date} } @builds;

    # get current pos
    my $curPos = 0;
    for (my $c = 0; $c <= $#builds; $c++) {
        if ($q->param('current') eq $builds[$c]->{name}) {
            $curPos = $c;
        }
    }

    # perform redirect based on vars
    if ($q->param('testing') eq "prev" and $curPos > 0) {
        print $q->redirect("http://test.winehq.org/data/".$builds[$curPos - 1]->{name});
        exit();
    } elsif ($q->param('testing') eq "next" and $curPos < $#builds) {
        print $q->redirect("http://test.winehq.org/data/".$builds[$curPos + 1]->{name});
        exit();
    } elsif ($q->param('testing') eq "latest") {
        print $q->redirect("http://test.winehq.org/data/".$builds[$#builds]->{name});
        exit();
    }
}

# redirect to data dir when no vars present
print $q->redirect("http://test.winehq.org/data/");
 
# done
exit();
