#!/usr/bin/perl

#
# WineTest Index Script
# by Jeremy Newman <jnewman@codeweavers.com>
#

# load CGI object
use CGI qw(:standard);
my $q = new CGI;

my $build = "";

# change url based on testing vars
if ($q->param('testing')) {

    my @builds;
    # read testing dir
    opendir(DIR, "./data/");
    foreach my $build (readdir(DIR))
    {
        next unless $build =~ /^[0-9a-f]{40}$/;
        next unless -f "./data/$build/index.html";
        push @builds, { name => $build, date => (stat "./data/$build")[9] };
    }
    closedir(DIR);
    @builds = sort { $a->{date} <=> $b->{date} } @builds;

    # get current pos
    my $curPos = 0;
    for (my $c = 0; $c <= $#builds; $c++) {
        if ($q->param('current') eq $builds[$c]->{name}) {
            $curPos = $c;
        }
    }

    # perform redirect based on vars
    if ($q->param('testing') eq "prev" and $curPos > 0) {
        $build = $builds[$curPos - 1]->{name};
    } elsif ($q->param('testing') eq "next" and $curPos < $#builds) {
        $build = $builds[$curPos + 1]->{name};
    } elsif ($q->param('testing') eq "latest") {
        $build = $builds[$#builds]->{name};
    }
    if ($build && $q->param('group') =~ /^[-_A-Za-z0-9]+$/) {
        my $index = "/index_" . $q->param('group') . ".html";
        $build .= $index if -f "./data/" . $build . $index;
    }
}

# redirect to data dir when no vars present
my $base = $q->url(-base => 1);
print $q->redirect($base . "/data/" . $build);
 
# done
exit();
