#!/bin/sh
#
# Send an email to the WineTestBot to let it know of new patches.
#
# Copyright 2010 Alexandre Julliard
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2.1 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the Free Software
# Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA

notify_addr="$1"
subject="New patches available at http://source.winehq.org/patches"
test -n "$notify_addr" || exit 0

old=`cat $HOME/.next-patch`
next=$old
while test -f /home/winehq/opt/source/patches/data/$next
do
    next=`expr $next + 1`
done
if test $next -gt $old
then
    echo $next >$HOME/.next-patch
    echo "The latest patch is `expr $next - 1`" | Mail -s "$subject" "$notify_addr"
fi
