#!/bin/sh

# This script is ran after a new release of Wine. It updates the website
# and FTP for the new wine release.

# usage: wine_release <version> [branch]

set -e
umask 002

if [ $# -lt 1 ]
then
  echo "Usage: $0 version [branch]"
  exit 1
fi

version=$1
branch=${2:-master}

website_dir="/home/winehq/opt/website"
templates_dir=$website_dir/templates
tools_dir="/home/winehq/opt/git-tools"

cd /home/winehq/opt/source

# update website config

sed "s/^${branch}_release:.*$/${branch}_release: $version/" $website_dir/include/globals.conf >globals.conf
mv -f globals.conf $website_dir/include/globals.conf

# nuke old attempt (if any)
rm -rf wine-$version

git clone -l -s -n git/wine.git wine-$version
(cd wine-$version && git checkout wine-$version)

# move wine link
rm -f wine
ln -s wine-$version wine

# make cross reference database for LXR
# note that we must have write permission in this directory
echo "==== UPDATING LXR ===="
cd db
rm -rf wine-$version
mkdir wine-$version
cd wine-$version
../../bin/genxref ../../wine-$version
chmod +r fileidx xref

# make Glimpse index
glimpseindex -n -H . ../../wine-$version
chmod +r .glimpse*
cd ../..

(echo "wine-$version"; cat wine-versions) | uniq > wine-versions.new && mv -f wine-versions.new wine-versions

cd wine-$version

if [ "$branch" = "master" ]
then
  # update man page and documentation
  echo "==== UPDATING DOCUMENTATION ===="
  ./configure --quiet --without-x --without-freetype
  make -s depend

  manpages="\
    loader/wine.man \
    loader/wine.de.UTF-8.man \
    loader/wine.fr.UTF-8.man \
    loader/wine.pl.UTF-8.man \
    server/wineserver.man \
    server/wineserver.de.UTF-8.man \
    server/wineserver.fr.UTF-8.man \
    tools/winemaker.man \
    tools/winemaker.de.UTF-8.man \
    tools/winemaker.fr.UTF-8.man \
    tools/widl/widl.man \
    tools/winebuild/winebuild.man \
    tools/winedump/winedump.man \
    tools/winegcc/winegcc.man \
    tools/wmc/wmc.man \
    tools/wrc/wrc.man"

  for f in $manpages
  do
    name=`basename $f .man`
    make -s -C `dirname $f` $name.man

    lang=`echo $name | cut -d . -f 2`
    if [ "$lang" = "$name" ]
    then lang="en"
    fi

    groff -man -T html -P -l -k -K utf8 $f | $tools_dir/html2template -o $name.template && mv -f $name.template $templates_dir/$lang/docs/`basename $name .$lang.UTF-8`.template
  done

  make -s htmlpages && rm -rf ../WineAPI && mv documentation/html ../WineAPI

  # Wine API Stats
  echo "==== UPDATING WINE API STATS PAGE ===="
  $tools_dir/winapi_stats > winapi_stats.template && mv -f winapi_stats.template $templates_dir/en/winapi_stats.template

  # cleanup source tree
  git clean -q -d -x -f
fi

rm -rf .git

# add version to bugzilla table
echo "INSERT INTO bugs.versions (value, product_id) VALUES(\"$version\",1)" | mysql

# end
