<?php

include("../lib.php");
include("../lib_res.php");

$DATAROOT = "..";

function res_enum($header, $f)
{
#    echo "Checking ".$header["type"]." ".$header["name"]."</br>\n";
    global $LOCALE_NAMES;
    if ($header["type"] != 6)
        return FALSE;
    if ($header["name"] != 1)
        return FALSE;
#    echo "Found resource for locale ".$header["language"]."<br/>\n";
    $data = fread($f, $header["resSize"]);
    $str = new StringTable($header, $data, 0);
    $langid = sprintf("%03x:%02x", $header["language"] & 0x3ff, $header["language"] >> 10);
    $LOCALE_NAMES[$langid] = $str->getString(2);
}

$LOCALE_NAMES = array();
$res = new ResFile("../dumps/res/dlls-kernel32-kernel.res");
$res->enumResources("res_enum");
ksort($LOCALE_NAMES);
echo "&lt;?php<br/># Generated by devel/dump-locales.php<br/>\$LOCALE_NAMES = array();<br/>";
foreach ($LOCALE_NAMES as $langid => $name)
{
    echo "\$LOCALE_NAMES[\"$langid\"] = ";
    dump_unicode($name);
    echo ";<br/>\n";

    $baseid = get_lang_base($langid);
    if (file_exists("$DATAROOT/conf/$baseid") && is_lang_ignore_sublang($baseid))
        echo "\$LOCALE_NAMES[\"".get_lang_base($baseid)."\"] = \$LOCALE_NAMES[\"$langid\"];   # ignore sublangs</br>\n";
}
echo "?&gt;";

?>