#!/bin/sh
#
# Update the LXR index after a new release of Wine.
# This should normally be run from a cron job.
#
# usage: update-version [<version>]
#

set -e
umask 002

gitdir=/home/winehq/opt/source/git/wine.git

if test -z "$1"
then
    version=$(git --git-dir=$gitdir tag --contains HEAD)
    if test -z "$version"
    then
        exit 0  # not a release tag
    fi
else
    version="wine-$1"
fi

cd /home/winehq/opt/source

(echo "$version"; cat wine-versions) | uniq > wine-versions.new
if cmp wine-versions wine-versions.new >/dev/null
then
    rm -f wine-versions.new
    exit 0  # already updated
fi

mv -f wine-versions.new wine-versions
./genxref --url=http://source.winehq.org --version="$version"
